<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://org.eclipselabs.eaadapter.model" nsPrefix="org.eclipselabs.eaadapter.model">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The package for the EA metamodel.&lt;br>&#xD;&#xA;&lt;code>EARepository&lt;/code> is the root element for all EA models.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;Note that the code generation templates are modified that way, that all &lt;i>volatile&lt;/i> features are &lt;i>disabled&lt;/i>!&lt;br>&#xD;&#xA;This makes it easy to deactivate certain attribute in the model without removing them.&#xD;&#xA;&lt;/div>"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EAAttribute" eSuperTypes="#//abstracthierachy/EAModifiableElement #//abstracthierachy/EAClassifierIDLong">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An attribute of the element.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For more detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCollection" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowDuplicates" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Attribute"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAAttributeTag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAAttributeTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_AttributeTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnector" eSuperTypes="#//abstracthierachy/EATypedElement #//abstracthierachy/EAMovableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A connector represents an association between two EAElements.&lt;br>&#xD;&#xA;The type (inherited attribute) defines what kind of connector it is. Examples are: &lt;code>Association, Generalization, Dependency&lt;/code or &lt;code>NoteLink&lt;/code>.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;&lt;b>Very important:&lt;/b> The EA takes care that no invalid models may exist. As a consequence, any Connector which has an invalid reference &lt;code>client&lt;/code> to the target EAElement will be 'garbage collected' by the EA!&#xD;&#xA;&lt;br>&lt;br>&lt;i>For more detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorID" eType="#//datatypes/Integer"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="#//datatypes/Boolean"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="#//datatypes/Boolean"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpec" eType="#//datatypes/Boolean"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualInheritance" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionEvent" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionAction" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionGuard" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeStyle" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceNo" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramID" eType="#//datatypes/Integer"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Connector"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAConnectorTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplierID" eType="#//datatypes/Integer"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" eType="#//EAElement"
        changeable="false" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This reference is handled as the opposite to the &lt;code>connectors&lt;/code> containment.&#xD;&#xA;If the containment changes, this references is updated as well.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplierEnd" eType="#//EAConnectorEnd"
        changeable="false" volatile="true" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientID" eType="#//datatypes/Integer"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="#//EAElement"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Reference to the target EAElement of this connector.&lt;br>&#xD;&#xA;&lt;b>Note:&lt;/b> Take care that this reference will always be valid, otherwise the EA takes care of it and 'garbage collects' it.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientEnd" eType="#//EAConnectorEnd"
        changeable="false" volatile="true" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_aggregation" eType="#//datatypes/Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_cardinality" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_containment" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_isNavigable" eType="#//datatypes/Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_note" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_role" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_roleType" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_stereotype" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_visibility" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>ClientEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_aggregation" eType="#//datatypes/Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_cardinality" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_containment" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_isNavigable" eType="#//datatypes/Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_note" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_role" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_roleType" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_stereotype" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier_visibility" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attribute of the &lt;b>SupplierEnd&lt;/b> object of type &lt;code>ConnectorEnd&lt;/code>.&lt;br>&#xD;&#xA;So, this is a wrapper attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isA2dDependency" eType="#//datatypes/Boolean"
        changeable="false" volatile="true" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Returns, whether the connection has the stereotype &lt;i>A2D&lt;/i> and is of the type &lt;i>dependency&lt;/i>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnectorEnd" eSuperTypes="#//abstracthierachy/EABaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="#//datatypes/String"
        defaultValueLiteral="Unspecified"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleType" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//datatypes/String"
        defaultValueLiteral="Public"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_ConnectorEnd"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="#//datatypes/String"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnectorTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_ConntectorTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EADiagram" eSuperTypes="#//abstracthierachy/EAOwnedElement #//abstracthierachy/EAStereotypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swimlanes" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//datatypes/String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//EAPackage"
        transient="true" eOpposite="#//EAPackage/diagrams"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Diagram"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramLinks" upperBound="-1"
        eType="#//EADiagramLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramObjects" upperBound="-1"
        eType="#//EADiagramObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EADiagramLink" eSuperTypes="#//abstracthierachy/EABaseClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//EAConnector"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorID" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geometry" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHidden" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_DiagramLink"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EADiagramObject" eSuperTypes="#//abstracthierachy/EABaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementID" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_DiagramObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAElement" eSuperTypes="#//abstracthierachy/EAClassifierIDLong #//abstracthierachy/EAOwnedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An Element can, for instance,  be a class, an interface or a UML Note.&lt;br>&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="#//datatypes/String"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This attribute is stored as a String type in the EA, not as a boolean - whyever!!!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierName" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierType" eType="#//datatypes/String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexity" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extensionPoints" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genlinks" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genfile" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gentype" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeEx" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tablespace" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//EAPackage"
        transient="true" eOpposite="#//EAPackage/elements">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The parent package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//EAAttribute" containment="true" eOpposite="#//EAAttribute/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//EAConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//EAElement" containment="true" eOpposite="#//EAElement/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//EAMethod" containment="true" eOpposite="#//EAMethod/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EATaggedValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Element"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasA2dDependency" eType="#//datatypes/Boolean"
        changeable="false" volatile="true" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Returns, whether this element has an ingoing or outgoing connector which has the stereotype &lt;i>A2D&lt;/i> and is of the type &lt;i>dependency&lt;/i>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" eType="#//datatypes/Integer"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageID" eType="#//datatypes/Integer"
        volatile="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAMethod" eSuperTypes="#//abstracthierachy/EAModifiableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An operation of the element it belongs to.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnIsArray" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throws" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPure" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynchronized" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrency" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierID" eType="#//datatypes/String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/methods"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Method"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//EAParameter" containment="true" eOpposite="#//EAParameter/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAMethodTag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAMethodTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_MethodTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAPackage" eSuperTypes="#//abstracthierachy/EAAbstractPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A package in EA is a container for other elements.&lt;br>&#xD;&#xA;A package can, for instance, be a UML package.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagrams" upperBound="-1"
        eType="#//EADiagram" volatile="true" containment="true" eOpposite="#//EADiagram/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//EAElement" containment="true" eOpposite="#//EAElement/package">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Set of contained elements.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//EAPackage" containment="true" eOpposite="#//EAPackage/package">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Subpackages of this package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//EAPackage"
        eOpposite="#//EAPackage/packages">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The parent package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Package"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The stereotype attribute is part of an object of type &lt;code>EAElement&lt;/code> which is referenced by each package.&lt;br>&#xD;&#xA;This object causes a lot of trouble because it has the same &lt;i>guid&lt;/i> as the package, so a wrapper getter and setter are generated by the code generation templates.&lt;br>&#xD;&#xA;As a consequence, the stereotype attribute can be used as a usual attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAParameter" eSuperTypes="#//abstracthierachy/EANamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Parameter of a method.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="#//datatypes/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//datatypes/Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="#//datatypes/Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//datatypes/String"
        volatile="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierID" eType="#//datatypes/String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationID" eType="#//datatypes/Integer"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//EAMethod"
        transient="true" eOpposite="#//EAMethod/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Parameter"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EARepository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Root object for an EA project.&lt;br>&#xD;&#xA;This object takes care of the link between the EMF model and the EA project.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eOperations name="openFile" eType="#//datatypes/Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Open the EA with the file given in the attribute &lt;code>file&lt;/code>.&lt;br>&#xD;&#xA;This method is not supposed to be called manually! It is used internally when the reference &lt;code>models&lt;/code> is accessed the first time.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="closeFile">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This closes the EA. Please do not call this manually - the behaviour is undefined.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="prefetch">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Manually perform the prefetching of all GUIDs defined by &lt;code>prefetchCompleteModel&lt;/code> or &lt;code>prefetchPackageGuids&lt;/code>.&lt;br>&#xD;&#xA;For more information, see documentation of the attribute &lt;code>prefetchingEnabled&lt;/code>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//EAPackage" transient="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Return all root packages of the project. Usually, this is only one package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Repository"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Specify the Enterprise Architect project file here.&lt;br>&#xD;&#xA;An absolut path is required!&lt;br>&#xD;&#xA;TODO: Implement support for relative paths and eclipse resource URIs.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;If the EA project specified in &lt;code>file&lt;/code> requires a authorized login, specify user name here.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;If the EA project specified in &lt;code>file&lt;/code> requires a authorized login, specify password here.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="caching" eType="#//datatypes/Boolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Any value that is read once from the EA will be cached in the corresponding EMF variable.&lt;br>&lt;br>&#xD;&#xA;If &lt;code>caching&lt;/code> is set to &lt;code>false&lt;/code>, any access to an attribute will re-access the EA to ask for the value.&#xD;&#xA;&lt;b>This is a lot slower! You should have a very good reason if you turn this feature off!&lt;/b>&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonlyEaLink" eType="#//datatypes/Boolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;All changes made in the model are &lt;i>not&lt;/i> transferred to the EA!&lt;br>&#xD;&#xA;This should be used in combination to the flag &lt;code>persistent&lt;/code> or for testing purposes only.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagrams" eType="#//datatypes/Boolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Not implemented yet!&lt;br>&#xD;&#xA;Idea: Support diagrams in the model.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefetchCompleteModel"
        eType="#//datatypes/Boolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;If this flag is set to &lt;code>true&lt;/code>, the guid's of all elements will be resolved at firs access of the reference &lt;code>models&lt;/code>.&lt;br>&#xD;&#xA;&lt;b>Warning:&lt;/b> This may take a long time if it is a huge model!&lt;br>&#xD;&#xA;Perhaps using &lt;code>prefetchPackageGuids&lt;/code> is a better choice.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;&lt;b>Note: This feature is still under development and may not work correctly!&lt;/b>&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefetchPackageGuids" eType="#//datatypes/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This attribute may contain a comma-separated list of packages to resolve at the first access of the reference &lt;code>models&lt;/code>.&lt;br>&#xD;&#xA;Examples:&#xD;&#xA;&lt;ul>&#xD;&#xA;&lt;li>Views.Logical_View.Analyse&#xD;&#xA;&lt;li>Views.Logical_View.Analyse.AWK, Views.Logical_View.Design&#xD;&#xA;&lt;/ul>&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" upperBound="-1"
        eType="#//Filter" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A filter reduces the set of specified children when a sub-collection is fetched &lt;b>the first time&lt;/b>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistentModels" upperBound="-1"
        eType="#//EAPackage" unsettable="true" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Do not use thie reference! See attribute &lt;code>persistent&lt;/code> for details!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;If this flag is set and the model is saved, the whole model (as it is resolved so far) will be saved into the file.&lt;br>&#xD;&#xA;Note: Saving works, but re-opening the file still fails!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefetchingEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This flag may temporarily used to avoid any prefetching when opening the model the first time.&lt;br>&#xD;&#xA;The falg is &lt;i>transient&lt;/i>! So it needs to be set each time the model is opened.&lt;br>&#xD;&#xA;Attention: If no prefetching takes place, a not already visited element cannot be resolved by its guid!&#xD;&#xA;But you can perform the prefetching process manually by calling &lt;code>prefetch()&lt;/code>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EATaggedValue" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_TaggedValue"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A filter can be used to reduce the adapter elements in EMF.&lt;br>&#xD;&#xA;Example: A filter can remove all model elements with a specific stereotype, for example the stereotype &quot;-X&quot;.&lt;br>&#xD;&#xA;If the filter is applied to all classes, each model element with the stereotype &quot;-X&quot; &lt;i>and its children&lt;/i> will not be transferred to the EMF model.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;This makes the model much more consice and speeds up the access because less elements are transferred.&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterClass" eType="#//datatypes/FilterClass"
        defaultValueLiteral="All">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Defines the class this filter should be applied to.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterType" eType="#//datatypes/FilterType"
        defaultValueLiteral="ContainsStringLiteral">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Defines the way this filter is applied:&#xD;&#xA;&lt;ul>&#xD;&#xA;&lt;li>&lt;code>EqualsStringLiteral&lt;/code> - The filter expression must be &lt;i>equal&lt;/i> to the filtered attribute.&#xD;&#xA;&lt;li>&lt;code>EqualsStringLiteral&lt;/code> - The filter expression must be &lt;i>contained&lt;/i> to the filtered attribute.&#xD;&#xA;&lt;li>&lt;code>EqualsStringLiteral&lt;/code> - The filter expression must &lt;i>match&lt;/i> (as a regular expression) to the filtered attribute.&#xD;&#xA;&lt;/ul>&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterAttribute" eType="#//datatypes/FilterAttribute"
        defaultValueLiteral="stereotype">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;What attribute should be filtered?&lt;br>&#xD;&#xA;Examples are &lt;code>name&lt;/code> and &lt;code>stereotype&lt;/code>.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;If you need to filter more attributes, add them to the enumeration &lt;code>FilterAttribute&lt;/code> in ea.ecore and adjust the template &lt;i>filterContainments.javajet&lt;/i>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterExpression" eType="#//datatypes/String"
        defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The filter expression.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negate" eType="#//datatypes/Boolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A filter can be negative. Only elements which match the filter expression are shown.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="datatypes" nsURI="http://org.eclipselabs.eaadapter.model.datatypes" nsPrefix="org.eclipselabs.eaadapter.model.datatypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EACollection" instanceClassName="org.sparx.Collection"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Attribute" instanceClassName="org.sparx.Attribute"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_AttributeTag" instanceClassName="org.sparx.AttributeTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Connector" instanceClassName="org.sparx.Connector"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_ConnectorEnd" instanceClassName="org.sparx.ConnectorEnd"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_ConntectorTag" instanceClassName="org.sparx.ConnectorTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Diagram" instanceClassName="org.sparx.Diagram"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_DiagramLink" instanceClassName="org.sparx.DiagramLink"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_DiagramObject" instanceClassName="org.sparx.DiagramObject"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Element" instanceClassName="org.sparx.Element"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Method" instanceClassName="org.sparx.Method"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_MethodTag" instanceClassName="org.sparx.MethodTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Package" instanceClassName="org.sparx.Package"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Parameter" instanceClassName="org.sparx.Parameter"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Repository" instanceClassName="org.sparx.Repository"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_TaggedValue" instanceClassName="org.sparx.TaggedValue"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EClass" instanceClassName="org.eclipse.emf.ecore.EClass"/>
    <eClassifiers xsi:type="ecore:EEnum" name="FilterClass">
      <eLiterals name="None"/>
      <eLiterals name="All" value="1"/>
      <eLiterals name="Element" value="2"/>
      <eLiterals name="Attribute" value="3"/>
      <eLiterals name="Method" value="4"/>
      <eLiterals name="Connector" value="5"/>
      <eLiterals name="TaggedValue" value="6" literal="TaggedValue"/>
      <eLiterals name="AttributeTag" value="7"/>
      <eLiterals name="MethodTag" value="8"/>
      <eLiterals name="ConnectorTag" value="9"/>
      <eLiterals name="Parameter" value="10"/>
      <eLiterals name="Package" value="11"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FilterType">
      <eLiterals name="EqualsStringLiteral"/>
      <eLiterals name="ContainsStringLiteral" value="1"/>
      <eLiterals name="RegexLiteral" value="2" literal="RegexLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FilterAttribute">
      <eLiterals name="name"/>
      <eLiterals name="stereotype" value="1"/>
      <eLiterals name="type" value="2"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="abstracthierachy" nsURI="http://org.eclipselabs.eaadapter.model.abstracthierachy"
      nsPrefix="org.eclipselabs.eaadapter.model.abstracthierachy">
    <eClassifiers xsi:type="ecore:EClass" name="EAAbstractPackage" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EAVersiondElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePath" eType="#//datatypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flags" eType="#//datatypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModel" eType="#//datatypes/Boolean"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EABaseClass" abstract="true" interface="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Base class for all adapter elements&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eOperations name="initializeAdapter" eType="#//datatypes/Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This initialized a new Element on the EA!&lt;br>&#xD;&#xA;This method is used internally to create new elements.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
        <eParameters name="collection" eType="#//datatypes/EACollection"/>
      </eOperations>
      <eOperations name="deleteAdapter" eType="#//datatypes/Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This deletes an element of the EA.&lt;br>&#xD;&#xA;Used internally!&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
        <eParameters name="collection" eType="#//datatypes/EACollection"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" eType="#//datatypes/String"
          changeable="false">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The objectType defines the EA type for each element.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//datatypes/Integer"
          changeable="false">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each EA element has a &lt;i>local&lt;/i> ID.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//EARepository"
          unsettable="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAClassifierIDLong" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EAVisibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierID" eType="#//datatypes/Integer"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAModifiableElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EAVisibilityElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="#//datatypes/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="#//datatypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EANamedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EABaseClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each element of the EA metamodel is a EANamedElement!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//datatypes/String"
          defaultValueLiteral="name">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The name of the EA element.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="#//datatypes/String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each EA element may have a note.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="#//datatypes/String"
          changeable="false" iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each element of the EA has a Global Unique IDendifier!&lt;br>&#xD;&#xA;This guid is used as an ID for the EMF model as well!&lt;br>&#xD;&#xA;Unfortunately, it is a readonly attribute for EA elements.&lt;br>&#xD;&#xA;&lt;b>Important: This attribute is set automatically if the adapter is initialized via &lt;code>initializeAdapter&lt;/code>!&lt;/b>&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAOwnedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EAVersiondElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="#//datatypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocked" eType="#//datatypes/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAStereotypedElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EANamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" eType="#//datatypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasDStereotype" eType="#//datatypes/Boolean"
          changeable="false" volatile="true" transient="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each stereotyped element can be checked whether the stereotype contains a '-X'.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EATaggedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EANamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//datatypes/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagID" eType="#//datatypes/Integer"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EATypedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EAStereotypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//datatypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAVersiondElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EANamedElement #//abstracthierachy/EAMovableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//datatypes/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAVisibilityElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EATypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//datatypes/String"
          defaultValueLiteral="Public"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAMovableElement" abstract="true"
        interface="true">
      <eOperations name="setNewParent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This can be used to move elements.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
        <eParameters name="parent" eType="#//abstracthierachy/EAVersiondElement"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
